# Pytorch Basic
Pytorch 기초 사용법

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'1.11.0'

In [4]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
nums.shape

torch.Size([9])

In [11]:
type(nums)

torch.Tensor

In [12]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [17]:
randoms = torch.rand((3,3))
randoms

tensor([[0.9959, 0.9330, 0.3267],
        [0.3950, 0.8972, 0.6554],
        [0.2110, 0.9952, 0.6369]])

In [20]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeros.size()

torch.Size([3, 3])

# Operations

In [25]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [26]:
nums = nums.reshape((3,3))

In [27]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [29]:
result = torch.add(nums,3)

In [31]:
result.numpy()

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# View : reshape과 동일하게 작용

In [32]:
range_nums = torch.arange(9).reshape(3,3)

In [33]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [34]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index

In [36]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
nums[1]

tensor([3, 4, 5])

In [38]:
nums[1,1]

tensor(4)

In [39]:
nums[1:,1:]

tensor([[4, 5],
        [7, 8]])

In [40]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

# Compile
numpy를 torch rensor로 불러오기

In [44]:
arr = np.array([1,1,1])

In [45]:
arr_torch = torch.from_numpy(arr)